name: biobb_workflows
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6
  - biobb_common==0.1.4
  - biobb_io==0.1.4
  - biobb_model==0.1.8
  - biobb_md==0.1.5
  - nglview
  - simpletraj
  - conda
